baseURL = 'https://juanbcdev.net.br/'
languageCode = 'en-us'
title = 'JuanBC'
theme = 'ananke'
debug = false
enableRobotsTXT = true
enableemoji = true
enableinlineshortcodes = true
relativeurls = true

[sitemap]
  changefreq = 'monthly'
  filename = 'sitemap.xml'
  priority = 0.5
